# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13oZ0dt1e7yYzCgjn7RbsursxSVNQT_hU
"""

def presentacion():
  print("Este es el modulo de nombre muy largo")